<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Core
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2024 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var \Bss\Core\Block\Adminhtml\Extensions $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<!-- ko scope: 'bsscore_extensions' -->
    <!-- ko template: getTemplate() --><!-- /ko-->
<!-- /ko-->

<script type="text/x-magento-init">
{
"*": {
    "Magento_Ui/js/core/app": {
            "components": {
                "bsscore_extensions": {
                    "component": "Bss_Core/js/extensions",
                    "promotionsData": <?= /* @noEscape */ $block->getPromotionsDataJson() ?>
                }
            }
        }
    }
}
</script>
